spring:
  application:
    name: sky-name
  profiles:
    active: dev

  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}




logging:
  level:
    com:
      wgc:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    admin-secret-key: wgc

    admin-ttl: 720000000

    admin-token-name: token


